version: 2.1
jobs:
  build:
    docker:
      - image: circleci/do-kubernetes-sample-app
    environment:
      IMAGE_NAME: ghcr.io/pakornpk/do-kubernetes-sample-app:latest
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            echo "START BUILD"
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "START RELEASE"
            echo "$PAT" | docker login ghcr.io -u $USERNAME --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-deploy-master:
    jobs:
      - build:
          filters:
            branches:
              only: master